require 'rake'

require 'magica/version'
require 'magica/package_config'
require 'magica/extension'
require 'magica/i18n'
require 'magica/dsl'
require 'magica/toolchain'
require 'magica/dependency'
require 'magica/application'

require 'magica/command'
require 'magica/commands/compiler'
require 'magica/commands/linker'
require 'magica/commands/git'
